version: '3.8'

services:
  app:
    build: .
    container_name: automationexercise-app
    depends_on:
      - mysql
    volumes:
      - .:/app
  mysql:
    image: mysql:8.0
    container_name: mysql-ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: automationexercise
    ports:
      - "3308:3306"
