server:
  port: 8080

spring:
  application:
    name: automationexercise
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://mysql-ecommerce:3306/automationexercise?serverTimezone=America/Lima&useSSL=false
    url: jdbc:mysql://db/automationexercise?serverTimezone=America/Lima&useSSL=false
    username: root
    password: yomer
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
